---
name: "Pre-Commit"

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup ASDF & Tools
        uses: asdf-vm/actions/install@v3.0.2
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v44.0.0
      - name: Run Pre-Commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }}
