---
name: Terraform Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

permissions: read-all

jobs:
  terraform-checks:
    uses: TheSoftwareHouse/github-actions/.github/workflows/terraform-checks.yaml@main
    with:
      working_dir: "."
